# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UTA_Query_GUI.ui'
#
# Created: Thu Apr 26 01:44:56 2018
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapQueryDialog(object):
    def setupUi(self, MapQueryDialog):
        MapQueryDialog.setObjectName(_fromUtf8("MapQueryDialog"))
        MapQueryDialog.resize(733, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("E:/UTA/SEM-2/6331/Project/UTA_Logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MapQueryDialog.setWindowIcon(icon)
        MapQueryDialog.setStyleSheet(_fromUtf8(""))
        self.label = QtGui.QLabel(MapQueryDialog)
        self.label.setGeometry(QtCore.QRect(130, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(MapQueryDialog)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(MapQueryDialog)
        self.label_3.setGeometry(QtCore.QRect(420, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.buildDescription = QtGui.QLineEdit(MapQueryDialog)
        self.buildDescription.setGeometry(QtCore.QRect(162, 80, 101, 21))
        self.buildDescription.setObjectName(_fromUtf8("buildDescription"))
        self.buildRadius = QtGui.QLineEdit(MapQueryDialog)
        self.buildRadius.setGeometry(QtCore.QRect(330, 80, 81, 22))
        self.buildRadius.setObjectName(_fromUtf8("buildRadius"))
        self.BuildName = QtGui.QLineEdit(MapQueryDialog)
        self.BuildName.setGeometry(QtCore.QRect(530, 80, 101, 22))
        self.BuildName.setObjectName(_fromUtf8("BuildName"))
        self.label_4 = QtGui.QLabel(MapQueryDialog)
        self.label_4.setGeometry(QtCore.QRect(130, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.buildType = QtGui.QLineEdit(MapQueryDialog)
        self.buildType.setGeometry(QtCore.QRect(160, 140, 113, 22))
        self.buildType.setObjectName(_fromUtf8("buildType"))
        self.label_5 = QtGui.QLabel(MapQueryDialog)
        self.label_5.setGeometry(QtCore.QRect(280, 140, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(MapQueryDialog)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.buildingOne = QtGui.QLineEdit(MapQueryDialog)
        self.buildingOne.setGeometry(QtCore.QRect(120, 190, 113, 22))
        self.buildingOne.setObjectName(_fromUtf8("buildingOne"))
        self.withinCombo = QtGui.QComboBox(MapQueryDialog)
        self.withinCombo.setGeometry(QtCore.QRect(30, 80, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.withinCombo.setFont(font)
        self.withinCombo.setObjectName(_fromUtf8("withinCombo"))
        self.withinCombo.addItem(_fromUtf8(""))
        self.withinCombo.addItem(_fromUtf8(""))
        self.typeCombo = QtGui.QComboBox(MapQueryDialog)
        self.typeCombo.setGeometry(QtCore.QRect(30, 140, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.typeCombo.setFont(font)
        self.typeCombo.setObjectName(_fromUtf8("typeCombo"))
        self.typeCombo.addItem(_fromUtf8(""))
        self.typeCombo.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(MapQueryDialog)
        self.label_7.setGeometry(QtCore.QRect(240, 190, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.buidlingTwo = QtGui.QLineEdit(MapQueryDialog)
        self.buidlingTwo.setGeometry(QtCore.QRect(310, 190, 121, 22))
        self.buidlingTwo.setObjectName(_fromUtf8("buidlingTwo"))
        self.label_8 = QtGui.QLabel(MapQueryDialog)
        self.label_8.setGeometry(QtCore.QRect(440, 190, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(MapQueryDialog)
        self.label_9.setGeometry(QtCore.QRect(130, 240, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.buildNearType = QtGui.QLineEdit(MapQueryDialog)
        self.buildNearType.setGeometry(QtCore.QRect(290, 240, 113, 22))
        self.buildNearType.setObjectName(_fromUtf8("buildNearType"))
        self.label_10 = QtGui.QLabel(MapQueryDialog)
        self.label_10.setGeometry(QtCore.QRect(420, 240, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.buildNearName = QtGui.QLineEdit(MapQueryDialog)
        self.buildNearName.setGeometry(QtCore.QRect(470, 240, 113, 22))
        self.buildNearName.setObjectName(_fromUtf8("buildNearName"))
        self.label_11 = QtGui.QLabel(MapQueryDialog)
        self.label_11.setGeometry(QtCore.QRect(590, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.queryResults = QtGui.QTextBrowser(MapQueryDialog)
        self.queryResults.setGeometry(QtCore.QRect(160, 300, 371, 192))
        self.queryResults.setObjectName(_fromUtf8("queryResults"))
        self.label_12 = QtGui.QLabel(MapQueryDialog)
        self.label_12.setGeometry(QtCore.QRect(30, 300, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_1 = QtGui.QPushButton(MapQueryDialog)
        self.pushButton_1.setGeometry(QtCore.QRect(650, 70, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet(_fromUtf8(""))
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.pushButton_2 = QtGui.QPushButton(MapQueryDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 130, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(MapQueryDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 180, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(_fromUtf8(""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(MapQueryDialog)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 230, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.nearCombo = QtGui.QComboBox(MapQueryDialog)
        self.nearCombo.setGeometry(QtCore.QRect(30, 240, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nearCombo.setFont(font)
        self.nearCombo.setObjectName(_fromUtf8("nearCombo"))
        self.nearCombo.addItem(_fromUtf8(""))
        self.nearCombo.addItem(_fromUtf8(""))

        self.retranslateUi(MapQueryDialog)
        QtCore.QMetaObject.connectSlotsByName(MapQueryDialog)

    def retranslateUi(self, MapQueryDialog):
        MapQueryDialog.setWindowTitle(_translate("MapQueryDialog", "UTA Map Queries", None))
        self.label.setText(_translate("MapQueryDialog", "all", None))
        self.label_2.setText(_translate("MapQueryDialog", "within", None))
        self.label_3.setText(_translate("MapQueryDialog", "(in meters) of", None))
        self.label_4.setText(_translate("MapQueryDialog", " all", None))
        self.label_5.setText(_translate("MapQueryDialog", "of type (e.g. academic/halls/parking).", None))
        self.label_6.setText(_translate("MapQueryDialog", "How far is", None))
        self.withinCombo.setItemText(0, _translate("MapQueryDialog", "List", None))
        self.withinCombo.setItemText(1, _translate("MapQueryDialog", "Display", None))
        self.typeCombo.setItemText(0, _translate("MapQueryDialog", "List", None))
        self.typeCombo.setItemText(1, _translate("MapQueryDialog", "Display", None))
        self.label_7.setText(_translate("MapQueryDialog", "from the", None))
        self.label_8.setText(_translate("MapQueryDialog", "?", None))
        self.label_9.setText(_translate("MapQueryDialog", "What are the nearest", None))
        self.label_10.setText(_translate("MapQueryDialog", "from", None))
        self.label_11.setText(_translate("MapQueryDialog", "?", None))
        self.label_12.setText(_translate("MapQueryDialog", "Query Results:", None))
        self.pushButton_1.setText(_translate("MapQueryDialog", "Go!", None))
        self.pushButton_2.setText(_translate("MapQueryDialog", "Go!", None))
        self.pushButton_3.setText(_translate("MapQueryDialog", "Go!", None))
        self.pushButton_4.setText(_translate("MapQueryDialog", "Go!", None))
        self.nearCombo.setItemText(0, _translate("MapQueryDialog", "List", None))
        self.nearCombo.setItemText(1, _translate("MapQueryDialog", "Display", None))

